import Foundation
import GlasshouseCore

// Emits build inputs and documentation from the capability ledger, so that the
// ledger is the only place any of it is written down.
//
//   swift run glasshouse-ledger plist          → App/Generated/Info.plist content
//   swift run glasshouse-ledger json           → the whole ledger, for tooling
//   swift run glasshouse-ledger checklist      → docs/device-verification.md
//   swift run glasshouse-ledger classification → docs/data-classification.md

/// The tier this build can actually sign. Changing this changes what ships.
let currentTier: SigningTier = .free

let command = CommandLine.arguments.dropFirst().first ?? "help"

switch command {
case "plist":
    try emitInfoPlist()
case "json":
    try emitJSON()
case "checklist":
    print(deviceChecklist())
case "classification":
    print(dataClassification())
default:
    FileHandle.standardError.write(Data("""
        usage: glasshouse-ledger <plist|json|checklist|classification>
        """.utf8))
    exit(1)
}

// MARK: - Info.plist

func emitInfoPlist() throws {
    let missing = UsageDescriptions.missing(for: currentTier)
    guard missing.isEmpty else {
        FileHandle.standardError.write(Data("""
            error: no usage description for: \(missing.joined(separator: ", "))
                   Add them to Sources/GlasshouseCore/Capability/UsageDescriptions.swift.

            """.utf8))
        exit(1)
    }

    var plist: [String: Any] = [
        "CFBundleDevelopmentRegion": "en",
        "CFBundleDisplayName": "Glasshouse",
        "CFBundleExecutable": "$(EXECUTABLE_NAME)",
        "CFBundleIdentifier": "$(PRODUCT_BUNDLE_IDENTIFIER)",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "$(PRODUCT_NAME)",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
        "UILaunchScreen": [String: Any](),
        "UIApplicationSceneManifest": ["UIApplicationSupportsMultipleScenes": false],
        "UISupportedInterfaceOrientations": [
            "UIInterfaceOrientationPortrait",
            "UIInterfaceOrientationLandscapeLeft",
            "UIInterfaceOrientationLandscapeRight",
        ],
    ]

    for key in CapabilityLedger.requiredPlistKeys(for: currentTier) {
        guard let description = UsageDescriptions.byKey[key] else { continue }

        // This one key is a dictionary of purpose-keyed strings, not a string.
        if key == "NSLocationTemporaryUsageDescriptionDictionary" {
            plist[key] = ["PrecisionDemonstration": description]
        } else {
            plist[key] = description
        }
    }

    let data = try PropertyListSerialization.data(
        fromPropertyList: plist, format: .xml, options: 0
    )
    FileHandle.standardOutput.write(data)
}

// MARK: - JSON export

func emitJSON() throws {
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    let data = try encoder.encode(CapabilityLedger.all.sorted { $0.id < $1.id })
    FileHandle.standardOutput.write(data)
    print()
}

// MARK: - Generated documentation

func deviceChecklist() -> String {
    let rows = CapabilityLedger.requiringDeviceVerification
    var out = """
        # Device verification checklist

        <!-- Generated by `swift run glasshouse-ledger checklist`. Do not edit. -->

        Everything the Simulator cannot prove. Work this list on first device
        deploy; each item is something whose behaviour is currently assumed
        rather than observed.

        \(rows.count) of \(CapabilityLedger.all.count) capabilities need hardware.

        """

    for (framework, capabilities) in CapabilityLedger.byFramework {
        let needing = capabilities.filter { !$0.isProvableInSimulator }
        guard !needing.isEmpty else { continue }
        out += "\n## \(framework)\n\n"
        for row in needing {
            let reason = row.simulator == .unavailable
                ? "framework or hardware absent"
                : "API present, no data delivered"
            out += "- [ ] **\(row.displayName)** (`\(row.id)`) — \(reason)\n"
            if let notes = row.notes {
                out += "      \(notes)\n"
            }
        }
    }

    out += """

        ## Also confirm on device

        These are not sensor readings, but they are the things a Simulator
        actively misleads about:

        - [ ] Entitlements actually resolve — the Simulator enforces none.
        - [ ] The app installs and launches under a free 7-day provisioning profile.
        - [ ] `LSApplicationWorkspace` returns an empty array (it returns real
              data in a Simulator, which is the trap).
        - [ ] `CBCentralManager.state` reaches `.poweredOn` rather than `.unsupported`.
        """
    return out
}

func dataClassification() -> String {
    var out = """
        # Data classification

        <!-- Generated by `swift run glasshouse-ledger classification`. Do not edit. -->

        Every capability by how much it reveals. Sensitivity drives storage
        protection and whether a stream is collected before the user asks for it.

        """

    for level in Sensitivity.allCases.reversed() {
        let rows = CapabilityLedger.all
            .filter { $0.sensitivity == level }
            .sorted { $0.id < $1.id }
        guard !rows.isEmpty else { continue }

        let stance = level.isEnabledByDefault
            ? "Collected by default."
            : "Off until explicitly enabled."
        out += "\n## \(level.rawValue.capitalized) — \(rows.count) capabilities\n\n\(stance)\n\n"

        for row in rows {
            let gate = row.promptsUser ? "prompts" : "**no prompt**"
            out += "- **\(row.displayName)** (`\(row.id)`, \(gate)) — \(row.reveals)\n"
        }
    }

    let silent = CapabilityLedger.silent.count
    out += """

        ## The part worth noticing

        \(silent) of \(CapabilityLedger.all.count) capabilities read without any
        permission dialog at all. That set — not the sensors behind prompts — is
        the most instructive thing this app has to show.
        """
    return out
}
